# If you only want to send a message to players who have permission "nmsg.receive"
use-permission: false
# Note: you can disable any message by clearing it
welcome: "&5Welcome &b%player% &5to our network!"
# Displayed to all players on BungeeCord (%player%, %to-server%)
join-all: "&e[&a+&e] &b%player% &7(&b%to-server%&7)"
# Displayed to all players on target server (%player%, %to-server%)
join-to: "&e[&a+&e] &b%player%"
# Displayed to all players on BungeeCord (%player%, %from-server%)
leave-all: "&e[&c-&e] &b%player% &7(&b%from-server%&7)"
# Displayed to all players on the server (%player%, %from-server%)
leave-from: "&e[&c-&e] &b%player%"
# Displayed to all players on BungeeCord (%player%, %from-server%, %to-server%)
switch-all: "&e[&7>&e] &b%player% &7> &b%to-server%"
# Displayed to all players on target server (%player%, %from-server%, %to-server%)
switch-to: "&e[&7>&e] &b%player% &7< &b%from-server%"
# Displayed to all players on the server (%player%, %from-server%, %to-server%)
switch-from: "&e[&7>&e] &b%player% &7> &b%to-server%"
# Servers
servers:
    factions:
        alias: "&2Factions&b"
        join-to: "&e%player% joined the game"
        switch-to: "&e%player% joined the game"